version: '2'
services:
  php:
    build: ./images/php
    restart: always
    volumes:
      - ./www:/var/www
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "8765:80"
      - "443:443"
    volumes:
      - ./hosts:/etc/nginx/conf.d
      - ./www:/var/www
    links:
      - php
